# Generated by Django 5.2.7 on 2025-10-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('AND', 'Em Andamento'), ('CON', 'Concluída')], default='PEN', max_length=3),
        ),
    ]
