# Generated by Django 5.2.7 on 2025-10-22 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_demanda_status'),
    ]

    operations = [
        # --- ADICIONE ESTA OPERAÇÃO PRIMEIRO ---
        migrations.RunSQL("UPDATE tarefas_demanda SET responsavel_id = NULL;"),
        # ----------------------------------------

        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='demanda',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarefas.profissional'),
        ),
    ]